Add Apache 2.0 license file to project root
ironcore-dev/libvirt-provider pull request #153
Opened 2024-02-05 09:01 UTC by afritzler

# Proposed Changes

Add Apache 2.0 license file to project root.

2024-02-05 09:02 UTC, lukasfrank approved these changes, later dismissed

2024-02-05 09:37 UTC, so-sahu approved these changes, later dismissed

2024-02-05 10:02 UTC, lukas016 submitted a review, later dismissed

2024-02-05 11:23 UTC, so-sahu requested changes
With the introduction of a dedicated License file, could we include a reference to it in the License section of the README file instead of having separate content there.

2024-02-05 13:23 UTC, afritzler commented
Good catch! Linked the license file in the Readme.

2024-02-06 04:55 UTC, so-sahu approved these changes

2024-02-06 08:59 UTC, merged