Bump dependencies
ironcore-dev/libvirt-provider pull request #413
Opened 2024-10-09 12:43 UTC by lukasfrank

# Proposed Changes

- Bump deps

2024-10-09 13:08 UTC, afritzler requested changes

2024-10-09 13:08 UTC, afritzler commented on go.mod
> -go 1.22.2
Just use `go 1.23.0`.

2024-10-09 13:08 UTC, afritzler commented on go.mod
> +require (
Merge this require block with the one above.

2024-10-10 08:26 UTC, afritzler approved these changes

2024-10-10 08:28 UTC, so-sahu approved these changes

2024-10-10 08:29 UTC, merged